server:
  port: 8001 
    
spring:  application:    name: microservicecloud-dept
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    instance-id:  microservicecloud-dept8001
    prefer-ip-address: true
    
info:
  app.name: hhf-microservicecloud
  company.name: https://www.demo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    